name: Check YAGPDB template syntax
description: Make sure YAGPDB template files have proper syntax
author: jo3-l
inputs:
  include:
    description: A glob for files to run the syntax checker on. The glob syntax is described by the documentation for the Match function provided by the Go library bmatcuk/doublestar.
    required: true
outputs:
  output:
    description: Output from the syntax checker
runs:
  using: docker
  image: Dockerfile
