// Code generated by gen_funcs.go; DO NOT EDIT.
package main

import (
	"github.com/jonas747/template"
)

var funcs = template.FuncMap{
	"hasRoleID": func(interface{}, interface{}, interface{}, interface{}, ...interface{}) string { return "" },
}
