name: Regenerate template functions

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  regenerate-funcs:
    name: Regenerate template functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run go generate
        run: go generate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          commit-message: 'chore: regenerate template functions'
          title: 'chore: regenerate template functions'
          body: |
            🤖 *beep boop*, this is an automated PR to regenerate the list of template functions.

            It may be prudent to tag a new version after merging this PR, which can be done from GitHub by triggering the release workflow from the Actions tab.
          branch: 'chore/regenerate-tmpl-funcs'
          delete-branch: true
          assignees: jo3-l
          reviewers: jo3-l
