name: Tag new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release; must be in the format vX.Y.Z'
        required: true

jobs:
  tag-new-release:
    name: Tag new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag new release
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! ${VERSION} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "invalid version supplied; must be in the format vX.Y.Z"
            exit 1
          fi

          git config --local user.name "${GITHUB_ACTOR}";
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          sed -i "s/$(git describe --tags --abbrev=0)/${VERSION}/" ./README.md
          git add ./README.md
          git commit -m "chore(release): ${VERSION}"

          git tag -a "${VERSION}" -m "chore(release): ${VERSION}";
          git push origin --follow-tags
